### ISSUE TITLE
Coverage not working

### ISSUE THREAD

**Issue by Mokto** [marcoturi/ionic2-boilerplate#20]
Hi,

After a git clone / npm install I can't run the `npm test` command properly. Unit tests are working but code coverage is not.

```bash
Finished in 0.024 secs / 0.263 secs

SUMMARY:
✔ 4 tests completed
19 12 2016 11:55:10.716:ERROR [coverage]: TypeError: remap is not a function
    at RemapCoverageReporter.onCoverageComplete (/home/theo/Documents/ionic2-boilerplate/node_modules/karma-remap-coverage/remap-coverage.js:23:23)
```

Am I missing something ? Thanks.

**Comment by marcoturi** [comment]
Could you try to change in package.json
"karma-remap-coverage": "^0.1.3",
in
"karma-remap-coverage": "0.1.3",

and run again npm install ? And see if it works ?

**Comment by Mokto** [comment]
I just did, same error unfortunately...

Thanks for your quick answer !

**Comment by marcoturi** [comment]
Reverting to "karma-remap-coverage": "0.1.2", fixed the issue. Let me know if you have further problems, and Thank you for opening the issue.

**Comment by Mokto** [comment]
It's working perfectly ! Thank YOU for fixing this in 15 minutes ! ;)
