### ISSUE TITLE
yarn failed on gitlab

### ISSUE THREAD

**Issue by eidng8** [marcoturi/ionic2-boilerplate#26]
gitlab builder complains:

```text
Running with gitlab-ci-multi-runner 1.9.4 (8ce22bd)
Using Docker executor with image marcoturi/ionic:latest ...
Pulling docker image marcoturi/ionic:latest ...
Running on runner-fa6cab46-project-2343902-concurrent-0 via runner-fa6cab46-machine-1485153937-388cca59-gce...
Cloning repository...
Cloning into '/builds/eidng8/ionic2-boilerplate'...
Checking out bf870f19 as master...
Checking cache for build_web/master...
Successfully extracted cache
$ yarn config set cache-folder yarn-cache
yarn config v0.19.1
success Set "cache-folder" to "yarn-cache".
Done in 0.05s.
$ yarn
yarn install v0.19.1
[1/5] Resolving packages...
[2/5] Fetching packages...
error "lodash-es-4.17.4.tgz": Tarball is not in network and can not be located in cache ("/builds/eidng8/ionic2-boilerplate/lodash-es-4.17.4.tgz")
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Build failed: exit code 1
```

with the [yml](https://gitlab.com/eidng8/ionic2-boilerplate/blob/5526ec639cb269990987634ada7c8a1e31818080/.gitlab-ci.yml)

anything needs to be touched on my side?

**Comment by marcoturi** [comment]
@eidng8 I can't see the yml file
- Did you tried to re-run the build? Sometimes gitlab has same network problem with npm/yarn packages. (Specially phantomjs)
- Are you running the build on your computer or default gitlab servers ?

**Comment by marcoturi** [comment]
https://github.com/yarnpkg/yarn/issues/652

**Comment by eidng8** [comment]
that yml file is from your repo, it's the file right after I've rebased. So it safe to just reference yours.

I do think this is a network problem. Because there were random (sort of) package popped up. Just was to confirm with you if there's anything I have to do, besides using your image.

**Comment by marcoturi** [comment]
Deleting and re-creating yarn.lock resolve the issue. See lasts commits.
