### ISSUE TITLE
Does tests get in the production build?

### ISSUE THREAD

**Issue by eidng8** [marcoturi/ionic2-boilerplate#27]
It seems that all tests will also be compiled during dev/prod build. Say, if I make a syntax error in the `home.spec.ts`, then run `npm run dev` or `ionic build android`, the error in the `home.spec.ts` will popup and breaks the build process.

**Comment by marcoturi** [comment]
The git flow suggested by this boilerplate is to push on production only after master's branch tests are passed. So the case you are suggesting is not possible and also the behaviour makes the build process safer to my point of view.
