### ISSUE TITLE
Wildcard for test files

### ISSUE THREAD

**Issue by superkew** [marcoturi/ionic2-boilerplate#3]
This repo is great but I tried without success to change the shim in such a way that I could specify wildcards for the spec files.

Being able to do something like this in the karma.conf file would be nice. Right now it seems like I need to manually import each test file into the shim.

```
files: [
'src/**/*.spec.ts'
]
```

**Comment by marcoturi** [comment]
Hi @superkew and thank you for opening an issue. Actually you can't import in es6 using wildcards. If you want to achieve this result you should build a bundle task to run before "npm run test" that bundle all spec files.
Ionic team is working on an a specific task in ionic app script for unit tests and e2e test based on angular cli.

**Comment by superkew** [comment]
It's a pity we can't use the normal karma imports for wildcards, but good to hear that ionic will be creating some tooling for us :)

**Comment by derksacklowski** [comment]
couldn't you do something like:

`        files: [
            'config/karma-shim.ts',
            'src/**/*.spec.ts'
        ],
        preprocessors: {
            'config/karma-shim.ts': ['rollup'],
            'src/**/*.spec.ts': ['rollup']
        },`

**Comment by rkostrzewski** [comment]
@superkew have a look at following [gist](https://gist.github.com/mfdeveloper/d9349dea78ba34a36adc7ada56ffd0c0#file-karma-conf-js) to achieve such glob support and still use rollup.

There is one problem with such solution tough - you'll have to somehow init test environment (as in current shim). Doing so in every test will throw an error as you can only do so once per test session. I ended up creating singleton for test environment initialization which based on static flag executes following:
`TestBed.initTestEnvironment(BrowserDynamicTestingModule,  platformBrowserDynamicTesting());
`

**Comment by marcoturi** [comment]
just run:
`npm run test:watch`

And now all your spec file are watched and loaded in karma-shim automatically.

**Comment by superkew** [comment]
Thank you!

**Comment by mfdeveloper** [comment]
Hey @marcoturi and @superkew . I submitted another approach to do this. The `karma-shim.ts` is not changed with the watch. I created a file that generate a `index.ts` with **`import`** statements. So, the `karma-shim.ts` contains only a simple `import ../src`.

Please, see my PR [!1](https://github.com/marcoturi/ionic2-boilerplate/pull/4) and check which the better approach to a standard structure :)
