### ISSUE TITLE
Cannot find module app.module.ngfactory

### ISSUE THREAD

**Issue by 1moere1** [marcoturi/ionic2-boilerplate#7]
I get the following Error in TSLint by the IDE:

`Error:(4, 36) TS2307: Cannot find module './app.module.ngfactory'.`

It's not something that is disturbing me but it still exists. Is there a way to prevent this?

**Comment by marcoturi** [comment]
The ngfactory is part of the ngc compilation and it's normal that it's missing from the src/app directory. I would like to have a way to not see that error, but it's more related to the ionic build system than the boilerplate. I suggest you to open an issue [here] (https://github.com/driftyco/ionic-app-scripts/issues).
